### ISSUE TITLE
MUSX extraction wrong !

### ISSUE THREAD

**Issue by elasriz** [pysathq/pysat#105]
Hello, I think I have a problem with mus extraction using MUSX and Optux. See the exemple below:

""" Start code
hards = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [-2, -5], [-2, -8], [-5, -8], 
        [-1, -4], [-1, -7], [-4, -7], [-3, -6], [-3, -9], [-6, -9], 
        [11], [12], [-13], [15], [-16], [-17], [20], [21], [-22], 
        [-24], [-25], [26], [-29], [-30], [31], [33], [34], [-35]]

softs = [[-5, -1, 22], [-1, -5, 11], [-1, -6, 12], [-6, -1, 25], 
        [-2, -4, 13], [-4, -2, 20], [-2, -6, 15], [-6, -2, 26], 
        [-3, -4, 16], [-4, -3, 21], [-3, -5, 17], [-5, -3, 24], 
        [-4, -8, 20], [-8, -4, 31], [-4, -9, 21], [-9, -4, 34], 
        [-5, -7, 22], [-7, -5, 29], [-5, -9, 24], [-9, -5, 35], 
        [-6, -7, 25], [-7, -6, 30], [-6, -8, 26], [-8, -6, 33]] 

wcnf = WCNF()
for hard in hards:
    wcnf.append(hard)
for soft in softs:
    wcnf.append(soft, weight = 1)
    
musx = MUSX(wcnf, verbosity=0)
mus = musx.compute()
print("MUS : \n",mus)

End code"""

When executing this code, I get [4, 5, 9, 17, 19, 21] as a MUS, but when I tried to verify this by removing clauses in MUS one by one and re-execute the code, I found that the problem remain UNSAT when removing 17, 19 or 21.
So I can conclude that the MUS is [4, 5, 9] and not [4, 5, 9, 17, 19, 21]

I am looking forward to your suggestions. Thanks.

**Comment by alexeyignatiev** [comment]
Hi @elasriz,

As far as I see, the MUS reported by MUSx is perfectly correct for the example you shared. The reason is that the hard clauses (`hards`) together with soft clauses 4, 5, and 9, i.e. with clauses `[-6, -1, 25], [-2, -4, 13], [-3, -4, 16]`, are satisfiable.

Moreover, all the 24 MUSes of this formula have the size of exactly 6. You can confirm this not only by running OptUx but also by invoking a CAMUS-like setup, i.e. by (1) enumerating MCSes and then (2) enumerating all minimal hitting sets. You can double-check this yourself as the set of MCSes is simple: `[[4], [5], [9], [21, 22], [1, 19, 20], [11, 12, 17, 18]]`.

Observe that every MUS includes clauses 4, 5, and 9 as these belong to unit-size MCSes.
