### ISSUE TITLE
Release version mismatch between pypi and github

### ISSUE THREAD

**Issue by hoodmane** [pysathq/pysat#156]
on pypi I see version 0.1.8.dev15 as the latest version. On github I see 0.1.7.dev15.

**Comment by alexeyignatiev** [comment]
It's because I made a GitHub release for Pyodide only and I haven't updated the version integrated in Pyodide for quite a while, @hoodmane. Right now, the plan is to add a number of features soon and push the version further up and then make another release on GitHub followed by updating the version in Pyodide. Is this okay with you, guys?

**Comment by hoodmane** [comment]
Thanks @alexeyignatiev!

**Comment by alexeyignatiev** [comment]
@hoodmane, I've submitted a [PR](https://github.com/pyodide/pyodide/pull/4641) to the pyodide repo bringing the latest version of PySAT.

**Comment by hoodmane** [comment]
Thanks @alexeyignatiev!
