### ISSUE TITLE
error upgrading to 0.1.4 from 0.0.4

### ISSUE THREAD

**Issue by kkew3** [pysathq/pysat#17]
Hi. When I tried to upgrading `python-sat`, I got the following error. Could someone help? Thank you so much!
[error.log](https://github.com/pysathq/pysat/files/3488864/error.log)

**Comment by alexeyignatiev** [comment]
Hi @kkew3. If I understand it correctly, the installer could not download one of the solvers (maplesat). There may be a number of things to cause this. Can you try to install the new version again? It will help me understand if the issue appears or not (and if yes, is it the same solver or not).

**Comment by kkew3** [comment]
Thanks for your reply. I confirm it occurs every time and gets stuck at exactly the same position. Is it possible to download maplesat manually so that I could find out why there's time out error? Thanks

**Comment by alexeyignatiev** [comment]
Thank you for the reply! Yes, you can do that if you clone the repository and try to manually install the framework with the use of ```setup.py``` (e.g. something like ```python setup.py install --prefix=.```).

For that, please, take a look at the file ```solvers/prepare.py```, which contains the list of solver archives that the script tries to download. The list is represented by variable ```sources```. Each item of the list is a pair, the first element of which is a URL while the second element is how the object should be saved locally. For example, MiniSat 2.2 is downloaded from http://minisat.se/downloads/minisat-2.2.0.tar.gz and is saved locally as ```solvers/minisat22.tar.gz```. MapleSAT is downloaded from https://sites.google.com/a/gsd.uwaterloo.ca/maplesat/MapleCOMSPS_pure_LRB.zip and is saved as ```solvers/maplesat.zip```.

As long as the archive files are saved locally with the right name, they will not be downloaded again. So if you want to build the framework manually and make sure the solver source archive is downloaded, you just need to save the target archive file the right way and try to build the framework using ```setup.py```. This should help to see where the problem is.

**Comment by kkew3** [comment]
Hi. Thanks a lot for your help! I tried it out. It turns out that the downloading code in prepare.py doesn't use system proxy settings. I can fetch all solvers with ease but it appears not the case for python code. Is it, by any means, possible to improve prepare.py? If not, I'm willing to leave the issue closed. Thanks again.

**Comment by kkew3** [comment]
Ah I see. I never noticed there's `--proxy` option in `pip`. Probably that helps. I'm closing this. Thanks for your help.

**Comment by alexeyignatiev** [comment]
Hi @kkew3. Great, thank you for letting me know! Did this solution work out in your case?

**Comment by kkew3** [comment]
Yes.

**Comment by alexeyignatiev** [comment]
Good to know, thank you!
