### ISSUE TITLE
On the usage of assumptions and literals (set_phases)

### ISSUE THREAD

**Issue by garandria** [pysathq/pysat#45]
Hello,

I would like to know if solving a formula with a list of
assumptions (code (1)) is semantically the same thing as using
`set_phases` with the same assumption literals (code (2)).

(1)
```Python
>>> s.solve(assumptions=[1, -2, 3])  # a SAT call with assumption literals
```

(2)

```Python
>>> s.set_phases(literals=[1, -2, 3])
>>> s.solve()
```

Thank you

**Comment by alexeyignatiev** [comment]
Hi @garandria,

No, these two pieces of code do different things. The former one (assumptions) can be seen as adding the 3 unit clauses `[1]`, `[-2]`, and `[3]` to the formula and then deciding if the formula with these additional clauses is satisfiable. Note that the clauses are not **really** added.

The latter one essentially sets a preference that we want to compute a model of the formula that assigns variable `1` to `True`, variable `2` to `False` and variable `3` to `True`. If there is no such model, the solver will eventually flip these values.

I presume this is not an issue of the toolkit. And so I close this. Otherwise, let me know.
