### ISSUE TITLE
Doing ^C (SIGINT) when running *solve_lim() causes segfault.

### ISSUE THREAD

**Issue by alexeyignatiev** [pysathq/pysat#55]
Interruption of *solve_lim() methods by pressing CTRL+C causes segmentation fault. The problem has something to do with the Py_BEGIN_ALLOW_THREADS and Py_END_ALLOW_THREADS macros.

**Comment by alexeyignatiev** [comment]
Hi @MiguelTerraNeves,

I noticed that if I interrupt a script while it is calling *solve_lim() function, I immediately get a segfault. To reproduce the issue, you can just interrupt `'lsu.py`. Do you know by any chance if there is a way to solve this issue? I am asking you because you added the macros Py_BEGIN_ALLOW_THREADS and Py_END_ALLOW_THREADS, to support timer-based interruption.

**Comment by alexeyignatiev** [comment]
OK, this should be fixed now by [87bca9b](https://github.com/pysathq/pysat/commit/87bca9bb3dd5ffb4d0eaddbc933954c1bfef74ed). As I am not an expert on Python GIL, I had to disable signal handling for limited SAT calls if those calls are expected to be interrupted by `interrupt()`.

**Comment by MiguelTerraNeves** [comment]
I'm not an expert with signal handling and the GIL so I would have to deep dive into this in order to fix the issue. Unfortunately I don't know when I'll be able to do this. Nonetheless, I'm fine with the current solution. I just have 1 minor comment.

This piece of code appears repeatedly somewhat often in `pysolvers.cc`:
```
PyOS_sighandler_t sig_save;
if (main_thread) {
	sig_save = PyOS_setsig(SIGINT, sigint_handler);

	if (setjmp(env) != 0) {
		PyErr_SetString(SATError, "Caught keyboard interrupt");
		return NULL;
	}
}
```

Maybe move this to a function and call that instead to avoid this repetition?

**Comment by alexeyignatiev** [comment]
Thanks for the suggestion. Will do that (or define a macro) once there is time. :)
