### ISSUE TITLE
Running pysat with PyPy

### ISSUE THREAD

**Issue by kopeckyf** [pysathq/pysat#57]
Since some of my SAT problems take some time, I thought it would be a nice idea to see if runtime can be improved by using PyPy instead of CPython. Unfortunately 

```
pypy3 -m pip install python-sat
```
fails.

Before pasting the extremely long setup/error log, I wanted to ask whether PyPy compatibility is even intended, i.e. if pysat installation under PyPy should even work in principle. 

My version is:
```
Python 3.6.9 (78d4c48fa091, Apr 30 2020, 07:55:31)
[PyPy 7.3.1 with GCC 10.0.1 20200328 (Red Hat 10.0.1-0.11)] on linux
```

**Comment by alexeyignatiev** [comment]
Unfortunately, PyPy is not supported. To be honest, it would be a pain to add support of PyPy. That would mean reimplementing the C extensions using something like CTypes or CFFI.

Regarding the performance, actually I don't think you can squeeze something out of moving to PyPy. If the bottleneck is a SAT call, it looks impossible to gain anything by changing the interpreter, even though PyPy is deemed to be more way more effective than CPython -- because SAT solvers are low-level and highly optimized pieces of code. However, I agree that you could improve the performance of the Python parts of your tool if PyPy was supported.

**Comment by blyxxyz** [comment]
Pysat does work in PyPy, at least on my machine with version:
```
Python 3.6.9 (7.3.1+dfsg-4, Apr 22 2020, 05:27:13)
[PyPy 7.3.1 with GCC 9.3.0]
```

If your log ends with something along these lines:
```
  cardenc/pycard.cc:14:10: fatal error: Python.h: No such file or directory
     14 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
```
then you're missing PyPy's development headers, which are e.g. packaged as `pypy3-dev` on Debian.

**Comment by alexeyignatiev** [comment]
@blyxxyz wow, it does work on PyPy3 indeed! At least, I managed to get it working on debian:buster in Docker. That's great! I still fail to compile it on macOS though...
