### ISSUE TITLE
Warm starting MAXSAT solvers

### ISSUE THREAD

**Issue by daniel-vos** [pysathq/pysat#72]
Hello, I am trying to solve a MAXSAT problem and so far am having great success with RC2 (thanks for the clean interface!). However, there is a good heuristic for this problem and so I would like to see if I can use this heuristic to speed up the search. As far as I understand RC2 and Fu&Malik are core-guided methods so they optimize the dual of the problem which means there is no use in starting them with a solution.

But I saw that there is also the LSU algorithm for MAXSAT. Is it possible to start this solver with a good initial guess? I currently did not see it mentioned in the documentation. Thanks!

**Comment by alexeyignatiev** [comment]
Hi @daniel-vos,
Thanks for this interesting question.
You are right in that RC2 and Fu&Malik are core-guided algorithms that mostly deal with unsatisfiable oracle calls. This makes it somewhat useless to use external models that would serve as a good approximation for a MaxSAT solution.
And yes, you are right that LSU can benefit if a good quality model is given at the beginning. If this is what you want to achieve, you can do something very simple along these lines:
```python
class LSUAugmented(LSU, object):
    """
        LSU augmented with the optional ability to apply a user-defined
        variable polarities to bootstrap the algorithm.
    """

    def __init__(self, formula, solver='g4', ext_model=[],
            expect_interrupt=False, verbose=0):
        """
            Constructor.
        """

        super(LSUAugmented, self).__init__(formula, solver=solver,
                expect_interrupt=expect_interrupt, verbose=verbose)

        if ext_model:
            # here we set user-defined polarities for some of 
            # (or all) the variables; if the polarities represent an actual
            # model, the solver will return it in the next SAT call
            self.oracle.set_phases(literals=ext_model)
```
Now, instead of standard base class `LSU`, just use the class `LSUAugmented` (see the source code, the interface should not differ too much from `RC2`. Also note that the current implementation of `LSU` can't handle formulas with weights larger than 1. Hope this helps.

**Comment by daniel-vos** [comment]
Great! I will try that.
