### ISSUE TITLE
Unnecessary clause in PBEnc.atmost

### ISSUE THREAD

**Issue by rjungbeck** [pysathq/pysat#73]
pysat.pb.PBEnc.atmost([1,2,3,4], bound=2, top_id=4).clauses

returns

````
[[5],
 [-1, -6],
 [-2, -6],
 [-1, -2, -7],
 [7, -8],
 [6, -3, -8],
 [7, -3, -9],
 [9, -10],
 [8, -4, -10],
 [10]]

````
At least the 1st clause [5] seems to be useless. It introduces an auxiliary variable that is never references again.

A similar problem is described in [issue 66](https://github.com/pysathq/pysat/issues/66)

**Comment by alexeyignatiev** [comment]
@rjungbeck, well, as you know, the `pb` module uses an external library, which I am not an author of. Also, the issue is not only in PySAT - it is actually not even in PyPBLib. The clauses mus be constructed in the original PBLib library. So this is where the issue pertains. As for [issue 66](https://github.com/pysathq/pysat/issues/66), it was about auxiliary variables in general, which is perfectly fine.

By the way, as far as I can see, you are using the `pb` module to encode a cardinality constraint and not a PB constraint. Why don't you use PySAT's internal module `card` instead? It is way more stable.
