### ISSUE TITLE
timer deprecation warning

### ISSUE THREAD

**Issue by tias** [pysathq/pysat#86]
when using python3.7 and solving with use_timer and all warnings enabled, I get:

  time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead

I guess some people may already be on 3.8?

**Comment by alexeyignatiev** [comment]
Hi Tias,

Which version of the toolkit are you using? This should be fixed for quite some time (since [December 4, 2019](https://pysathq.github.io/news.html#id17)). Here is what is currently in the source code:

```python
try:  # for Python < 3.8
    from time import clock as process_time
except ImportError:  # for Python >= 3.8
    from time import process_time
```

I do use Python 3.9.6 and it does not complain in my case. I presume your setup has an older version of the interpreter, and it shows all the warnings.

**Comment by tias** [comment]
Alright, then it is a non-issue.

I guess you could swap the order of the imports, as python 3.7 already has the newer one.

Then again, I should upgrade my base system beyond python 3.7 ; )


Kind regards,
Tias
