### ISSUE TITLE
CardEnc.atmost and equals with large bound

### ISSUE THREAD

**Issue by mvcisback** [pysathq/pysat#91]
Hello,

I'm seeing weird/surprising behavior with `CardEnc.atmost` and `CardEnc.atleast` where it seems to truncate the bound, e.g., `sum(x) >= bound` or `sum(x) == bound` to the length of `x`.

Is this intended? I was expecting it to a clauses that is trivially unsat or through a `ValueError`.

**Comment by alexeyignatiev** [comment]
Hi @mvcisback, can you give concrete examples of what you mean?

**Comment by mvcisback** [comment]
```python
from pysat.solvers import Glucose4
from pysat.card import CardEnc


with Glucose4() as f:
    f.append_formula(CardEnc.equals([1,2,3], 10), no_return=True)
    print(f.solve())  # Prints True
```

@alexeyignatiev

**Comment by alexeyignatiev** [comment]
Let's what happens.

It makes perfect sense to me that constraint `x1 + x2 + x3 <= 10` should be represented by an empty CNF as there is no way to falsify it, no matter how we assign the three variables.

The problem lies in `x1 + x2 + x3 >= 10`. This obviously should be an unsatisfiable formula but the question is: _how to represent it in CNF_? PySAT encodes AtLeast constraints by translating them to AtMost constraints first. In this case, I guess it tries to encode `-x1 + -x2 + -x3 <= -7` and obviously does something weird.

I need to think about this.
