### ISSUE TITLE
unable to install PySAT on Cygwin64

### ISSUE THREAD

**Issue by bios8086** [pysathq/pysat#93]
I installed all the prerequisites in my Cygwin64. I still received the following  errors. See the attachments,

![20211031070135](https://user-images.githubusercontent.com/7280748/139570413-d2900808-6312-407a-9177-7490ddf830f3.png)
![20211031070145](https://user-images.githubusercontent.com/7280748/139570416-f57232a1-7cf1-4738-b46a-deef2e1fd9db.png)
![20211031070156](https://user-images.githubusercontent.com/7280748/139570418-9f23e5ed-26d5-4b27-b8b5-2770b7af8a44.png)

**Comment by alexeyignatiev** [comment]
Hi @bios8086. Well, it may indeed be the case that the toolkit is currently not compilable on Cygwin64. Unfortunately, I personally don't have a way to check this. I find it weird though as I thought Cygwin should support the necessary POSIX functionality.

**Comment by ChrisJefferson** [comment]
The problem is that (technically) putc_unlocked isn't part of standard C++, and cygwin is stricter about this.

The fix is to search+replace `-std=c++11` with `-std=gnu++11`, which enables "gnu extension" (I believe this shouldn't break any other OS, but this type of thing can be fiddly). Note that using `gnu++x` (for differing values of `x`) is the default behaviour of gcc.

**Comment by ChrisJefferson** [comment]
This describes the issue (if you'd like more details) https://stackoverflow.com/questions/33658930/putchar-unlocked-doesnt-work-in-c-14-standard

**Comment by alexeyignatiev** [comment]
@ChrisJefferson, thanks a lot for investigating! Do you mean it is safe to replace the standard and it will continue compiling successfully on all the systems where it worked plus it will additionally compile on Cygwin? 😄
