### ISSUE TITLE
WCNF from_fp doesn't properly read from a file without explicit topw

### ISSUE THREAD

**Issue by DavidFerrerBeltran** [pysathq/pysat#98]
The function [from_fp](/pysathq/pysat/blob/1c1dd0aebe077ca72ca743af4283a46bccf88bf9/pysat/formula.py#L1109) doesn't properly read Weighted Max-SAT ._wcnf_'s that have no explicit _topw_, using their number of clauses as _topw_.
In a ._wcnf_ file such as:
```
c comments Weighted Max-SAT
p wcnf 3 4
10 1 -2 0
3 -1 2 -3 0
0.8 -3 2 0
5.6 1 3 0
```
from http://www.maxhs.org/docs/wdimacs.html, it would parse 4 as _topw_ and take the first and last clauses as hard clauses.
The expected behaviour would be instead taking all clauses as soft.

**Comment by alexeyignatiev** [comment]
Thank you for reporting this, @DavidFerrerBeltran. I should say that this is an example of a wrong preamble line because there must be a top weight specified (according to the format description of [MaxSAT evaluations](https://maxsat-evaluations.github.io/2021/rules.html#input)). But we should definitely try to avoid issues even in this problematic case. So thanks for the fix as well!
